In [2]:
import matplotlib.pyplot as plt
import numpy as np


from aart_func import *
import params
from params import * # The file params.py contains all the relevant parameters for the simulations
from astropy import units as u
import kgeo
import image_tools as tls
import subprocess
import scipy.interpolate

from matplotlib import ticker
from matplotlib.lines import Line2D

%load_ext autoreload
%autoreload 2
import importlib 
from functools import partial

In [12]:
t = np.zeros(3)
t = np.vstack((t,np.array([1,1,1])))
print(t)
print("_________")
t = np.delete(t,0,0)
print(t)

[[0. 0. 0.]
 [1. 1. 1.]]
_________
[[1. 1. 1.]]


In [14]:
'{:.2f}'.format(3)

'3.00'